deploy:
  provider: heroku
  app: ancient-ravine-4945
  run: rake db:migrate
  api_key:
    secure: TnHqFGjeMRzo/qMrp0lfb8aNLAJaeyabxWpezOhZxXkhQVx50YQlaES7MTz+xIrrzqo+jPKF0pM7n2wlRgYiDCN0q6L6a2ctrNawkT/JNBsND+mBVdIzmg44fH+Y8KfEHTbMz1n5chza8mAyknMTZ1fWMQefD0X5H9PCdbS0pkg=
language: ruby
rvm:
- 2.1.3
addons:
  postgresql: '9.3'
before_script:
- psql -c 'create database travis_ci_test;' -U postgres
env:
- DATABASE_URL=postgresql://postgres@localhost/travis_ci_test
notifications:
  slack:
    secure: WzqPoeFIXVDfcsIVdEuqMVzn1QlXIpzRkQAW5TWQoDTK42udNRPjfW2I1uIY4gk7NFXL9qN7pT10iJFnA5gWUFu4PQhSx/OETn6oJ1MEHil4G6CLTJ47ODSqmWBuJes9crS4/yyAvqXgmvKjg7dQEH2Oq4mrBOEA1lAxceR1+1c=
bundler_args: --without development
